#!/usr/bin/env bash
#
# Produce a drop-in single-file AES library (mbedtls_aes.c + mbedtls_aes.h)
# from the pristine TF-PSA-Crypto sources. No files in the submodule are
# modified.
#
# SPDX-FileCopyrightText: Frank Hunleth
# SPDX-License-Identifier: CC0-1.0
#
# Steps:
#   1. Copy the three upstream .c files into a scratch dir.
#   2. Apply patches in numeric order (flat patches/NNNN-*.patch layout).
#   3. Concatenate with banners:
#        generator/mbedtls_aes.h.in      (copied through verbatim)
#        upstream aes.c                  (post-patch)
#        x86 target-attribute pragma push
#        upstream aesni.c                (post-patch)
#        x86 target-attribute pragma pop
#        upstream aesce.c                (post-patch; already self-wraps
#                                         its own clang target pragma)
#        generator/platform_util_min.c
#
# Output: repo-root {mbedtls_aes.c,mbedtls_aes.h}

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
UPSTREAM="$REPO/TF-PSA-Crypto/drivers/builtin/src"
PATCHES="$HERE/patches"
OUT="$REPO"

if [ ! -d "$UPSTREAM" ]; then
    echo "error: TF-PSA-Crypto submodule not checked out" >&2
    echo "       run: git submodule update --init" >&2
    exit 1
fi

# Record the exact submodule commit in the output so drift is visible in
# generated-file diffs.
UPSTREAM_SHA="$(git -C "$REPO/TF-PSA-Crypto" rev-parse HEAD 2>/dev/null || echo unknown)"

# Derive the upstream repo URL from .gitmodules so the banner URLs still work
# if the submodule is re-pointed. SSH form gets converted to HTTPS.
UPSTREAM_REPO_URL="$(git config --file "$REPO/.gitmodules" submodule.TF-PSA-Crypto.url 2>/dev/null || echo)"
case "$UPSTREAM_REPO_URL" in
    git@github.com:*) UPSTREAM_REPO_URL="https://github.com/${UPSTREAM_REPO_URL#git@github.com:}" ;;
esac
UPSTREAM_REPO_URL="${UPSTREAM_REPO_URL%.git}"
: "${UPSTREAM_REPO_URL:=https://github.com/Mbed-TLS/TF-PSA-Crypto}"
UPSTREAM_SRC_URL="$UPSTREAM_REPO_URL/blob/$UPSTREAM_SHA/drivers/builtin/src"

SELF_REPO_URL="$(git -C "$REPO" config --get remote.origin.url 2>/dev/null || echo)"
case "$SELF_REPO_URL" in
    git@github.com:*) SELF_REPO_URL="https://github.com/${SELF_REPO_URL#git@github.com:}" ;;
esac
SELF_REPO_URL="${SELF_REPO_URL%.git}"
: "${SELF_REPO_URL:=https://github.com/fhunleth/mbedtls_aes}"

SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

# Stage upstream files.
cp "$UPSTREAM/aes.c"   "$SCRATCH/"
cp "$UPSTREAM/aesni.c" "$SCRATCH/"
cp "$UPSTREAM/aesce.c" "$SCRATCH/"

# Apply patches in order. -F 0 disallows fuzz so upstream drift fails loudly
# instead of silently producing a miss-aligned patch.
for p in "$PATCHES"/*.patch; do
    echo "applying $(basename "$p")"
    (cd "$SCRATCH" && patch -p1 -F 0 --no-backup-if-mismatch < "$p")
done

mkdir -p "$OUT"

banner() {
    printf '\n/* ========================================================================\n *  %s\n * ======================================================================== */\n\n' "$1"
}

# Shared provenance block prepended to both generated files.
write_provenance() {
    printf '/*\n'
    printf ' * Generated by generator/amalgamate.sh. Do not edit directly —\n'
    printf ' * change the patches or generator sources and regenerate.\n'
    printf ' *\n'
    printf ' * Amalgamator source:     %s\n' "$SELF_REPO_URL"
    printf ' * Original source code:   %s\n' "$UPSTREAM_SRC_URL"
    printf ' * TF-PSA-Crypto commit:   %s\n' "$UPSTREAM_SHA"
    printf ' */\n'
}

# Produce mbedtls_aes.h with the provenance banner prepended.
{
    write_provenance
    echo
    cat "$HERE/mbedtls_aes.h.in"
} > "$OUT/mbedtls_aes.h"

{
    banner "mbedtls_aes.c — amalgamated from TF-PSA-Crypto"
    write_provenance

    banner "Begin aes.c (from TF-PSA-Crypto/drivers/builtin/src/aes.c)"
    cat "$SCRATCH/aes.c"

    banner "Begin aesni.c (from TF-PSA-Crypto/drivers/builtin/src/aesni.c)"
    cat <<'EOF'
/* The AES-NI body uses intrinsics that require target features which may not
 * be enabled by the command-line -march/-m flags. Push per-function target
 * attributes so this translation unit compiles on a plain x86_64 build. */
#if defined(MBEDTLS_AESNI_C) && defined(MBEDTLS_AESNI_HAVE_CODE) && \
    (MBEDTLS_AESNI_HAVE_CODE == 2)
#  if defined(__clang__)
#    pragma clang attribute push (__attribute__((target("sse2,aes,pclmul"))), apply_to=function)
#    define AMALG_AESNI_PRAGMA_CLANG
#  elif defined(__GNUC__)
#    pragma GCC push_options
#    pragma GCC target ("sse2,aes,pclmul")
#    define AMALG_AESNI_PRAGMA_GCC
#  endif
#endif
EOF
    cat "$SCRATCH/aesni.c"
    cat <<'EOF'
#if defined(AMALG_AESNI_PRAGMA_CLANG)
#  pragma clang attribute pop
#  undef AMALG_AESNI_PRAGMA_CLANG
#endif
#if defined(AMALG_AESNI_PRAGMA_GCC)
#  pragma GCC pop_options
#  undef AMALG_AESNI_PRAGMA_GCC
#endif
EOF

    banner "Begin aesce.c (from TF-PSA-Crypto/drivers/builtin/src/aesce.c)"
    cat "$SCRATCH/aesce.c"

    banner "Begin platform_util (hand-written minimal replacement)"
    cat "$HERE/platform_util_min.c"

} > "$OUT/mbedtls_aes.c"

lines_c=$(wc -l < "$OUT/mbedtls_aes.c")
lines_h=$(wc -l < "$OUT/mbedtls_aes.h")
echo "wrote $OUT/mbedtls_aes.c ($lines_c lines) and $OUT/mbedtls_aes.h ($lines_h lines)"
